### PR TITLE
feat: finished version

### PR DESCRIPTION
**Pull request by Mhera17**
## Description
finished version

### CODE REVIEW

**Review by eburck — CHANGES_REQUESTED** [review]
Hello @Mhera17 , 

CI pipeline reports:
[vite]: Rollup failed to resolve import "lodash" from "/home/circleci/project/src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesRightTime_v2.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "lodash" from "/home/circleci/project/src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesRightTime_v2.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///home/circleci/project/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:44636:19)
    at onwarn (file:///home/circleci/project/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:44407:13)
    at Object.onwarn (file:///home/circleci/project/node_modules/rollup/dist/es/shared/node-entry.js:24950:13)
    at ModuleLoader.handleInvalidResolvedId (file:///home/circleci/project/node_modules/rollup/dist/es/shared/node-entry.js:23632:26)
    at file:///home/circleci/project/node_modules/rollup/dist/es/shared/node-entry.js:23592:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.

Is 'lodash' accidently imported in src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesRightTime_v2.tsx as you dropped it with https://github.com/trustedshops-public/connect-app-connector/pull/41?

**Comment by Mhera17** [comment]
@eburck  sonarCloud bugs are still there. I will try again

**Comment by eburck** [comment]
@Mhera17 , Thank you for latest changes - build now works. However, sonarCloud bugs are still there. How should we move on with it?

**Comment by Mhera17** [comment]
Hi @eburck @DomiKoch. I'm researching how to fix it. I will write here later.

**Pull request merged**
